# Práctica Clase 2

1) Abrir el archivo "Emisiones_CO2.csv" y cargar sus datos en un diccionario.

In [ ]:
with open('Emisiones_CO2.csv','r') as file:
    data = file.read()
data

In [67]:
archivo = open('Emisiones_CO2.csv', 'r', encoding='latin-1') # r -> read; w -> write; rt -> read text; wb -> write binary

In [68]:
dicc_emisiones = {  'cod_pais' : [], #0
                    'nom_pais' : [], #1
                    'region' : [], #2
                    'anio' : [], #3
                    'co2' : [],#4
                    'co2_percapita' : []}#5

In [37]:
dicc_emisiones['cod_pais'].append(campo[0])

[]

In [ ]:
campo = ['ABW','Aruba','América Latina y Caribe','1960']
campo[0]

In [69]:
next(archivo) #Eliminamos el encabezado (o los nombres de las columnas)
for linea in archivo:
    linea = linea.strip()
    campos = linea.split(sep='|')
    dicc_emisiones['cod_pais'].append(campos[0])
    dicc_emisiones['nom_pais'].append(campos[1])
    dicc_emisiones['region'].append(campos[2])
    dicc_emisiones['anio'].append(campos[3])
    dicc_emisiones['co2'].append(campos[4])
    dicc_emisiones['co2_percapita'].append(campos[5])


In [49]:
i = 110
print(dicc_emisiones['cod_pais'][i])
print(dicc_emisiones['nom_pais'][i])
print(dicc_emisiones['region'][i])
print(dicc_emisiones['anio'][i])
print(dicc_emisiones['co2'][i])
print(dicc_emisiones['co2_percapita'][i])

AFG
Afganistán
Sur de Asia
1966
1.092,77
0,10767397



In [51]:
if True:
    print('Holaaa')
else:
    print('Chaauu')

Chaauu


In [ ]:
if encabezado == False --> if not encabezado

In [ ]:
archivo = open('Emisiones_CO2.csv', 'r', encoding='latin-1')
conta = 0
encabezado = True #Bandera
for linea in archivo:
    if encabezado == False: # if not encabezado; if conta > 2:
        linea = linea.strip()
        campos = linea.split(sep='|')
        dicc_emisiones['cod_pais'].append(campos[0])
        dicc_emisiones['nom_pais'].append(campos[1])
        dicc_emisiones['region'].append(campos[2])
        dicc_emisiones['anio'].append(campos[3])
        dicc_emisiones['co2'].append(campos[4])
        dicc_emisiones['co2_percapita'].append(campos[5])
    else:
        encabezado = False # conta += 1

In [52]:
archivo.close()

2) a) ¿Cuántas variables hay? <br>
b) ¿Qué tipos de datos usar para cada una? <br>
c) ¿Qué tipo de variables son? <br>
d) ¿Hay valores faltantes? <br>
e) ¿Cuál es el total de emisiones de CO2 para 'América Latina y Caribe' en el año 2010?

In [54]:
print(f'La cantidad de variables existentes es de: {len(dicc_emisiones.keys())}')

La cantidad de variables existentes es de: 6


In [55]:
print('La cantidad de variables existentes es de: {0}'.format(len(dicc_emisiones.keys())))

La cantidad de variables existentes es de: 6


In [62]:
i = 0
print(dicc_emisiones['cod_pais'][i])
print(dicc_emisiones['nom_pais'][i])
print(dicc_emisiones['region'][i])
print(dicc_emisiones['anio'][i])
print(dicc_emisiones['co2'][i])
print(dicc_emisiones['co2_percapita'][i]) # '\n'

ABW
Aruba
América Latina y Caribe
1960
None




In [70]:
for indice, elemento in enumerate(dicc_emisiones['co2']):
    # 1.092,77
    elemento = elemento.replace('.','') # 1092,77
    elemento = elemento.replace(',','.') # 1092.77 -> str
    if elemento != '':
        elemento = float(elemento) 
    else:
        elemento = None
    dicc_emisiones['co2'][indice] = elemento

# 1.092.77

In [71]:
for indice, elemento in enumerate(dicc_emisiones['co2_percapita']):
    elemento = elemento.replace('\n','') #'0,10767397\n'
    elemento = elemento.replace('.','')
    elemento = elemento.replace(',','.')
    if elemento != '':
        elemento = float(elemento)
    else:
        elemento = None

    dicc_emisiones['co2_percapita'][indice] = elemento


cod_pais: Cualitativa - Categórica

nom_pais: Cualitativa - Categórica

region: Cualitativa - Categórica 

anio: Cuantitativa - Discreto

co2: Cuantitativa - Continuo

co2_percapita: Cuantitativa - Continuo


In [72]:
[type(i[110]) for i in dicc_emisiones.values()]

[str, str, str, str, float, float]

In [75]:
contador=0

for k in dicc_emisiones.keys():
    for v in dicc_emisiones[k]:
        if v==None or v=='\n':
            contador+=1

print(f'Existen {contador} valores faltantes')

Existen 4193 valores faltantes


In [78]:
filtro_region = 'América Latina y Caribe'#1
filtro_anio = '2010' #2
contador = 0

for indice, elemento in enumerate(dicc_emisiones['region']):
    if (dicc_emisiones['region'][indice] == filtro_region) and (dicc_emisiones['anio'][indice] == filtro_anio) and (dicc_emisiones['co2'][indice] != None):
        contador += dicc_emisiones['co2'][indice]
    
print(f'La cantidad total de emisiones en {filtro_region} para el año {filtro_anio} fueron de {contador}kt')

La cantidad total de emisiones en América Latina y Caribe para el año 2010 fueron de 1691634.8009999995kt


In [79]:
contador = 0
for indice, elemento in enumerate(dicc_emisiones['region']):
    if (dicc_emisiones['region'][indice] == filtro_region):
        if (dicc_emisiones['anio'][indice] == filtro_anio):
            if (dicc_emisiones['co2'][indice] != None):
                contador += dicc_emisiones['co2'][indice]
    
print(f'La cantidad total de emisiones en {filtro_region} para el año {filtro_anio} fueron de {contador}kt')

La cantidad total de emisiones en América Latina y Caribe para el año 2010 fueron de 1691634.8009999995kt


In [ ]:
suma_co2 = 0

for linea in archivo:
    campos = linea.split('|')
    if 'América Latina y Caribe' in campos and '2010' in campos:
        co2_str = campos[4].replace('.', '')  # Eliminar las comas de los miles
        co2_str = co2_str.replace(',', '.')  # Reemplazar el punto decimal por un punto
        if co2_str != '' or co2_str != '\n':
            co2 = float(co2_str)
            suma_co2 += co2



print("La suma de la columna 'co2' es:", suma_co2)


In [80]:
%pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [82]:
import numpy as np

In [84]:
my_list = [1,2,3,4,5,6]
arr = np.array(my_list)
print(arr)

[1 2 3 4 5 6]


In [91]:
print(np.arange(start=2,stop=10,step=1))

[2 3 4 5 6 7 8 9]


In [94]:
print(np.linspace(0,1,11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [92]:
print(np.zeros(6))

[0. 0. 0. 0. 0. 0.]


In [93]:
print(np.ones(4))

[1. 1. 1. 1.]


In [96]:
arr = np.ones(4)
print(type(arr[0]))

<class 'numpy.float64'>


In [100]:
print(np.full(shape=(2,4), fill_value=7))

[[7 7 7 7]
 [7 7 7 7]]


In [120]:
print(np.linspace(start=1,stop=10,num=10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [110]:
base = np.linspace(start=2,stop=6,num=5)
print(base)

[2. 3. 4. 5. 6.]


In [126]:
base = np.full(shape=(2,6), fill_value=4.41) # Array base dimension (2,6) y valores 4.41


print(np.full_like(base, '5')) # Array que toma su dimension (2,6) y lo llena con un valor (np.pi)

[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [115]:
print(base)

[[4.41 4.41 4.41 4.41 4.41 4.41]
 [4.41 4.41 4.41 4.41 4.41 4.41]]


In [144]:
print(np.random.rand(4,2))

[[0.85715403 0.08201984]
 [0.36699599 0.28918863]
 [0.7679411  0.60207474]
 [0.37440525 0.10718633]]


In [ ]:
print(np.random.randint())

In [149]:
print(np.random.uniform(low=0, high=10, size=(2,2)))

[[9.58510989 3.08136342]
 [0.98474617 7.15247698]]


In [147]:
print(np.random.randn(4,2))

[[ 0.96793339 -0.90315148]
 [-0.9137118   0.02101676]
 [-0.60041987 -0.51687325]
 [-0.35282153  1.26117845]]


In [157]:
print(np.random.normal(loc=5, scale=2, size=6)) # Dist normal

[6.7422238  5.90613371 5.70033488 0.86992293 5.21175229 5.87002723]


In [159]:
arr = np.arange(1,10)
print(arr)
print(arr.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [166]:
b = np.reshape(arr, [3,3])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [163]:
print(arr.dtype)

int32


In [182]:
matrix = np.arange(16).reshape(4,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [168]:
print(matrix[1,2])

5


In [169]:
print(matrix[2,1])

7


In [171]:
print(matrix[1])

[3 4 5]


In [178]:
print(matrix[:,2])

[2 5 8]


In [180]:
print(matrix[1:2, 1:])

[[4 5]]


In [195]:
matrix_b = matrix.copy()

In [190]:
matrix_b = matrix

In [196]:
print(id(matrix_b))
print(id(matrix))

1828374233712
1828387247312


In [185]:
a = np.arange(5,10)

In [187]:
print(a)
print(a + 10)

[5 6 7 8 9]
[15 16 17 18 19]


In [189]:
b = np.full(4, 3)
c = np.ones(4, dtype='int')
print(b)
print(c)

[3 3 3 3]
[1 1 1 1]


In [197]:
print(b - c)

[2 2 2 2]


In [198]:
print(np.matmul(b,c))

12


In [200]:
a = np.array([[2,3],[2,3],[2,3]])
b = np.array([[1,6,5,2,7],[1,2,7,0,9]])

print(np.matmul(a, b))

[[ 5 18 31  4 41]
 [ 5 18 31  4 41]
 [ 5 18 31  4 41]]


In [201]:
print(a@b) # Es lo mismo q matmul

[[ 5 18 31  4 41]
 [ 5 18 31  4 41]
 [ 5 18 31  4 41]]


In [204]:
print(a)
print('-------')
print(a.T) # Transpuesta (intercambia filas por columnas en una matriz)

[[2 3]
 [2 3]
 [2 3]]
-------
[[2 2 2]
 [3 3 3]]


In [205]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [206]:
print(a / 2)
print(a // 2)


[0.  0.5 1.  1.5]
[0 0 1 1]


In [207]:
print(a ** 2)

[0 1 4 9]


In [208]:
print(-a)

[ 0 -1 -2 -3]


In [209]:
print(a % 2)

[0 1 0 1]


In [211]:
print(a-10)

[-10  -9  -8  -7]


In [213]:
abs(-a)

array([0, 1, 2, 3])

In [215]:
heigh_list = [1.70,1.85,1.90,1.65,1.48,1.75,1.69,1.84,1.73,1.79,1.62,1.59]

print(np.mean(heigh_list))

1.7158333333333333


In [216]:
print(np.median(heigh_list))

1.7149999999999999


In [217]:
print(np.std(heigh_list))

0.11550312646081155


In [218]:
print(np.percentile(heigh_list, q=90))

1.8490000000000002


In [221]:
print(np.exp(heigh_list)) # Valor exponencial



[5.47394739 6.35981952 6.68589444 5.20697983 4.39294568 5.75460268
 5.41948071 6.29653826 5.64065391 5.98945247 5.05309032 4.90374893]


In [222]:
print(np.log(heigh_list)) # Logaritmo natural

[0.53062825 0.61518564 0.64185389 0.50077529 0.39204209 0.55961579
 0.52472853 0.60976557 0.54812141 0.58221562 0.48242615 0.46373402]


In [220]:
print(np.sqrt(heigh_list)) # Raíz cuadrada

[1.30384048 1.36014705 1.37840488 1.28452326 1.21655251 1.32287566
 1.3        1.356466   1.31529464 1.33790882 1.27279221 1.26095202]


In [237]:
b = np.random.uniform(low=1.9, high=2.0, size=12)
a = np.random.uniform(low=1.4, high=2.0, size=12)

In [238]:
print(np.greater(a, b))

[False False False False False False False False  True False  True False]


In [243]:
a = np.arange(0,20).reshape(2,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [251]:
mask = ((a % 2) == 0)
print(mask)

[[ True False  True False  True False  True False  True False]
 [ True False  True False  True False  True False  True False]]


In [252]:
print(a[mask]) # Aplicamos la mascara al array

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# < > >= <= == != (operadores logicos)